notifications:
  email: false

dist: trusty
sudo: true

#addons:
#  apt:
#    packages:
#      - libssh2

language: php

php:
  #- 5.5
  - 5.6
  #- 7.0
  #- 7.1

env:
  matrix:
    -
    #- DEPENDENCIES=--prefer-lowest

matrix:
  fast_finish: true

cache:
  directories:
    - .composer/cache

install:
  - sudo apt-get install -y libssh2
  - yes '' | pecl install ssh2
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer update $DEPENDENCIES

script:
  - composer test -- --coverage-clover=build/logs/clover.xml

after_success:
  - composer require satooshi/php-coveralls
  - vendor/bin/coveralls -v
