notifications:
  email: false

sudo: false

addons:
  apt:
    packages:
      - libssh2-1-dev

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    -
    - DEPENDENCIES=--prefer-lowest

matrix:
  fast_finish: true

cache:
  directories:
    - .composer/cache

install:
  - yes '' | pecl install ssh2 > /dev/null
  - alias composer=composer\ -n && composer selfupdate
  - composer validate
  - composer update $DEPENDENCIES

script:
  - composer test -- --coverage-clover=build/logs/clover.xml

after_success:
  - composer require satooshi/php-coveralls
  - vendor/bin/coveralls -v
